spring:
  datasource:
    username:
      postgres
    password:
      postgres
    url:
      jdbc:postgresql://localhost:5431/postgres
  jpa:
    hibernate:
      ddl-auto:
        create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
